# Generated by Django 5.0.6 on 2024-07-02 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_user_client_id'),
        ('foundation', '0002_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='status',
            new_name='statuss',
        ),
    ]
