# Generated by Django 5.0.6 on 2024-07-03 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0005_department_client_id_designation_client_id_and_more'),
        ('core', '0001_initial'),
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complexity_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foundation.complexity'),
        ),
        migrations.AddField(
            model_name='task',
            name='department_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.department'),
        ),
        migrations.AddField(
            model_name='task',
            name='feature_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.feature'),
        ),
        migrations.AddField(
            model_name='task',
            name='issue_source_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foundation.issue_source'),
        ),
        migrations.AddField(
            model_name='task',
            name='issue_stage_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foundation.issue_stage'),
        ),
        migrations.AddField(
            model_name='task',
            name='issue_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foundation.issue_type'),
        ),
        migrations.AddField(
            model_name='task',
            name='priority_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foundation.priority'),
        ),
        migrations.AddField(
            model_name='task',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.project'),
        ),
        migrations.AddField(
            model_name='task',
            name='sdlc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foundation.sdlc'),
        ),
        migrations.AddField(
            model_name='task',
            name='solution_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.solution'),
        ),
        migrations.AddField(
            model_name='task',
            name='status_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foundation.statuss'),
        ),
        migrations.AddField(
            model_name='task',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.user'),
        ),
        migrations.AddField(
            model_name='usecase',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client'),
        ),
        migrations.AddField(
            model_name='usecase',
            name='feature_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.feature'),
        ),
        migrations.AddField(
            model_name='usecase',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.project'),
        ),
        migrations.AddField(
            model_name='usecase',
            name='sdlc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foundation.sdlc'),
        ),
        migrations.AddField(
            model_name='usecase',
            name='solution_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.solution'),
        ),
        migrations.AddField(
            model_name='usecase',
            name='status_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foundation.statuss'),
        ),
        migrations.AddField(
            model_name='task',
            name='usecase_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.usecase'),
        ),
    ]
