# Generated by Django 5.0.6 on 2024-06-30 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_user_client_id'),
        ('core', '0004_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='task',
            new_name='feature',
        ),
    ]
