# Generated by Django 5.0.6 on 2024-07-03 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usecase'),
        ('foundation', '0009_issue_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecase',
            name='sdlc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foundation.sdlc'),
        ),
        migrations.AddField(
            model_name='usecase',
            name='status_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foundation.statuss'),
        ),
    ]
