# Generated by Django 5.0.6 on 2024-07-03 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project_id',
        ),
    ]
