# Generated by Django 5.0.6 on 2024-07-03 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_task_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.project'),
        ),
    ]
