# Generated by Django 5.0.6 on 2024-06-27 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_remove_client_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='client_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.user'),
        ),
    ]
