# Generated by Django 5.0.6 on 2024-07-03 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_department_client_id_designation_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='client_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client'),
        ),
    ]
