# Generated by Django 5.0.6 on 2024-06-30 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_user_department_id_user_designation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.user'),
        ),
    ]
